name: Build .NET MAUI App

on:
  push:
    branches: [ master ]
    paths:
      - 'IISchedule/**'
      - '.github/workflows/**'

  pull_request:
    paths:
      - 'IISchedule/**'
      - '.github/workflows/**'

env:
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  CSPROJ_TO_BUILD: IISchedule/IISchedule.csproj
  PROJECT_FOLDER: IISchedule/
  ANDROID_PLATFORM: net8.0-android
  WINDOWS_PLATFORM: net8.0-windows
  IOS_PLATFORM: net8.0-ios
  MAC_CATALYST_PLATFORM: net8.0-maccatalyst

jobs:
  build-ci:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install .Net MAUI
        run: dotnet workload install maui

      - name: Install Newtonsoft NuGet package
        run: dotnet add ${{ env.CSPROJ_TO_BUILD }} package Newtonsoft.Json
      - name: Install Mopups NuGet package
        run: dotnet add ${{ env.CSPROJ_TO_BUILD }} package Mopups
      - name: Install CommunityToolkit.Maui NuGet package
        run: dotnet add ${{ env.CSPROJ_TO_BUILD }} package CommunityToolkit.Maui
      - name: Install Refractored.MvvmHelpers NuGet package
        run: dotnet add ${{ env.CSPROJ_TO_BUILD }} package Refractored.MvvmHelpers
        
      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_FOLDER }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build for Android
        run: dotnet build ${{ env.CSPROJ_TO_BUILD }} -c ${{ env.BUILD_CONFIGURATION }} -f ${{ env.ANDROID_PLATFORM }} --no-restore
